# Generated by Django 5.1.7 on 2025-03-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppRestaurante", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("1", "ENTRADA"),
                            ("2", "PLATO FUERTE"),
                            ("3", "POSTRE"),
                        ],
                        max_length=1,
                        verbose_name="Categoría",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="vehiculo",
        ),
    ]
