# Generated by Django 5.1.7 on 2025-03-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("1", "Entrada"),
                            ("2", "Plato Fuerte"),
                            ("3", "Postre"),
                            ("4", "Bebida"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
