# Generated by Django 5.2 on 2025-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppRestaurante", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plato",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("PRINCIPAL", "Principal"),
                    ("POSTRE", "Postre"),
                    ("BEBIDA", "Bebida"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="plato",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
