# Generated by Django 5.2 on 2025-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppRestaurante", "0002_alter_plato_categoria_alter_plato_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="plato",
            name="imagen",
            field=models.URLField(blank=True, null=True),
        ),
    ]
